### ISSUE TITLE
Update giving error and not updating

### ISSUE THREAD

**Issue by pvuorio** [pilotak/homeassistant-clientraw#11]
Hello

I have had the clientraw running for 4 days on my local network but yesterday it stopped updating the values.

Having following error in LOG:
>Traceback (most recent call last):
>File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
>await asyncio.shield(task)
>File "/config/custom_components/clientraw/sensor.py", line 107, in async_setup_platform
>await weather.async_update()
>File "/config/custom_components/clientraw/sensor.py", line 380, in async_update
>new_state = float(self.data[3])
>ValueError: could not convert string to float: '--'

From what i know i have not changed anything in the config.
Config part is straight copied from your readme (locally located):

- platform: clientraw
    url: "http://192.168.11.193/weewx/clientraw.txt"
    interval: 10
    monitored_conditions:
      - dewpoint
      - heat_index
      - temp
      - temp_indoor
      - temp_day_max
      - temp_day_min
      - humidex
      - wind_degrees
      - wind_dir
      - wind_gust_hour
      - wind_gust_day
      - wind_speed
      - wind_speed_avg_10min
      - symbol
      - rain_rate
      - daily_rain
      - yesterday_rain
      - monthly_rain
      - yearly_rain
      - pressure
      - humidity
      - humidity_indoor
      - cloud_height
      - forecast

Is there anything i have done wrong or setup from my side is wrong?
Exist also online same version of the clientraw.txt.
h**p://www.pvuorio.net?weewx?clientraw.txt

Regards

Patrick

**Comment by pilotak** [comment]
There is nothing wrong with your config, I noticed that too, but on my side it's working for about 2 weeks. This behavior started to pop out by January this year, something must have happened in the core. Simple restart helps for the time being

**Comment by pvuorio** [comment]
Hello 

Noticed that i restarted at 4:40 and it came back for a while at 9:00 then again at 9:48 it froze.
Seems random.

Traceback (most recent call last):
  File "/config/custom_components/clientraw/sensor.py", line 380, in async_update
    new_state = float(self.data[3])
ValueError: could not convert string to float: '--'

Anyway i will monitor it.

Looked in line 380 and it is '-' and error is '--' can this be it? (probably in my clientraw is double -- when no wind)

**Comment by pilotak** [comment]
Ok so I did an investigation and your error differs to mine. Mine is due to lack of connection to the internet because of the VPN tunnel. Yes you are right about single/double dash. I looked at your file and you even have a tripple dash.

I have updated the code, in `catch_invalid` branch, could you please test it?

**Comment by pvuorio** [comment]
Ok,
Downloaded and replaced files in clientraw directory

This is what comes in LOG after restart

2021-11-22 17:04:15 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up clientraw platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/clientraw/sensor.py", line 107, in async_setup_platform
await weather.async_update()
File "/config/custom_components/clientraw/sensor.py", line 380, in async_update
new_state = float(self.data[3])
ValueError: could not convert string to float: '--'

UPDATE:

After full restart of raspberry it seems to be working as i have 0.0 m/s wind now

R
Patrick

**Comment by pvuorio** [comment]
Hello

Now it have run through the night and I am still having the same issue when wind at 0.
You mentioned updated the code, I am not really sure i got the new code as the one here is 9 months old it says and date stamp is 11/3 on the file. 
Suspect i do not have your latest updated code

R
Patrick

**Comment by pilotak** [comment]
https://github.com/pilotak/homeassistant-clientraw/blob/catch_invalid/custom_components/clientraw/sensor.py

**Comment by pvuorio** [comment]
Hello,

Inserted the new code and it has now been running for about 24h and with wind speeds of 0.
All seems so far to be working.

Thanks again for the effort. of solving my issue.
R
Patrick

**Comment by pilotak** [comment]
perfect, i will release it
