### ISSUE TITLE
Ha 11.23 shows invalid config - mentions Clientraw

### ISSUE THREAD

**Issue by NotFU1** [pilotak/homeassistant-clientraw#30]
Updated HomeAssistant tonight to 
Core 2023.11.0
Supervisor 2023.10.1
Operating System 11.1
Frontend 20231030.1

Checking config and it shows

Check and restart
A basic validation of the configuration is automatically done before restarting. The basic validation ensures the YAML configuration doesn't have errors which will prevent Home Assistant or any integration from starting. It's also possible to only do the basic validation check without restarting.

**Configuration invalid!**
Platform error sensor.clientraw - No module named 'homeassistant.util.distance'

Is any one else seeing this??

I have pretty much the example settings in my configuration.yaml - nothing added except path to file.  Was working fine before update.

Excuse me if i have not filled out correctly as this is my first time posting on here.

**Comment by pilotak** [comment]
> Was working fine before update.

Yes it did, updates always breaks something as usual... I could not find any info how to solve it at the moment, i would need to investigate, which will time. But i'm happy to accept PR meanwhile

**Comment by pilotak** [comment]
fixed in v2.6.0 thanks @fiLLLip

**Comment by NotFU1** [comment]
Thanks all for the quick response. community is great.
But I must be doing something wrong.. after seeing the PR come through and getting notification via my local HASS to update wich i did..
rebooted
i then uncommented the lines in configuration.yaml. and checked again and still have the warning.
"Platform error sensor.clientraw - No module named 'homeassistant.util.distance'
Double checked that the versions are correct on my instance of HASS
Removed the clientraw integration and re-added, rebooted and checked the config again with same results.. i feel kind of stupid as I am sure I must be doing something wrong but just cant see it. Still learning here.
Any thoughts??
Do I possibly need to remove the folders completely after removing the integration and try again fresh.
Many thanks guys.

**Comment by pilotak** [comment]
should be ok in v2.6.1m thanks for feedback

**Comment by NotFU1** [comment]
I saw the version change to .1 and d/loaded and yes its working again.  Many Thanks for the support.
